name: C/C++ CI cmake

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    - name: cmake
      run: mkdir build && cd build && cmake ..
    - name: make
      run: cd build && make
